CREATE DATABASE IF NOT EXISTS `{MYSQL_DATABASE}`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '{MYSQL_USER}'@'%' IDENTIFIED BY '{MYSQL_PASSWORD}';
ALTER USER '{MYSQL_USER}'@'%' IDENTIFIED BY '{MYSQL_PASSWORD}';

REVOKE ALL PRIVILEGES ON `{MYSQL_DATABASE}`.* FROM '{MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON `{SYSTEM_DB_GRANT_PATTERN}`.* TO '{MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON `{TENANT_DB_GRANT_PATTERN}`.* TO '{MYSQL_USER}'@'%';

FLUSH PRIVILEGES;
